backend:
  name: github #git-gateway
  repo: MKLab-ITI/hugomklab
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with /images/uploads  
collections:
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "content/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Types", name: "types", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Created at", name: "date", widget: "datetime"}
      - {label: "Featured image", name: "images", widget: "image", "required": false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "publication" # Used in routes, e.g., /admin/collections/blog
    label: "Publication" # Used in the UI
    folder: "content/publications" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Types", name: "types", widget: "hidden", default: "publication"}
      - {label: "Title", name: "title", widget: "string", hint: "Publication title only. No authors, dates, etc..."}
      - {label: "Created at", name: "date", widget: "datetime"}
      - label: "Tag"
        name: "tags"
        widget: "select"
        options:
          - { label: "Conference", value: "conference_publications" }
          - { label: "Journal", value: "journal_publications" }
          - { label: "Book chapter", value: "book_chapters" }
          - { label: "Proceedings, books, white papers", value: "proceedings_books_white_papers" }
          - { label: "Patents", value: "patents" }
      - {label: "Publication Date", name: "publication_date", widget: "date", format: "DD/MM/YYYY", hint: "Ordering is based on this field"}
      - {label: "Body", name: "body", widget: "markdown", "hint": "You should avoid extreme formatting in publication body text"}